# Generated by Django 5.2.11 on 2026-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('action_taken', models.TextField(blank=True, help_text='Actions taken or planned')),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_reported', '-severity'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('safety', 'Safety'), ('operational', 'Operational'), ('workshop', 'Workshop'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
